float_feats = [
    'latitude_air', 'longitude_air', 'GP_air_lv1_ON_latitude_mean',
    'GP_air_lv1_ON_latitude_max', 'GP_air_lv1_ON_latitude_min',
    'GP_air_lv1_ON_longitude_mean', 'GP_air_lv1_ON_longitude_max',
    'GP_air_lv1_ON_longitude_min', 'GP_air_lv2_ON_latitude_mean',
    'GP_air_lv2_ON_latitude_max', 'GP_air_lv2_ON_latitude_min',
    'GP_air_lv2_ON_longitude_mean', 'GP_air_lv2_ON_longitude_max',
    'GP_air_lv2_ON_longitude_min', 'GP_air_lv3_ON_latitude_mean',
    'GP_air_lv3_ON_latitude_max', 'GP_air_lv3_ON_latitude_min',
    'GP_air_lv3_ON_longitude_mean', 'GP_air_lv3_ON_longitude_max',
    'GP_air_lv3_ON_longitude_min', 'latitude_hpg', 'longitude_hpg',
    'GP_latitude_longitude_ON_hpg_store_id_count',
    'GP_hpg_lv1_ON_hpg_store_id_count',
    'GP_hpg_lv1_hpg_lv2_ON_hpg_store_id_count',
    'GP_hpg_lv1_hpg_lv2_hpg_lv3_ON_hpg_store_id_count',
    'GP_hpg_genre_name_ON_hpg_store_id_count',
    'GP_hpg_genre_name_hpg_lv1_ON_hpg_store_id_count',
    'GP_hpg_genre_name_hpg_lv1_hpg_lv2_ON_hpg_store_id_count',
    'GP_hpg_genre_name_hpg_lv1_hpg_lv2_hpg_lv3_ON_hpg_store_id_count',
    'GP_hpg_lv1_ON_latitude_mean', 'GP_hpg_lv1_ON_latitude_max',
    'GP_hpg_lv1_ON_latitude_min', 'GP_hpg_lv1_ON_longitude_mean',
    'GP_hpg_lv1_ON_longitude_max', 'GP_hpg_lv1_ON_longitude_min',
    'GP_hpg_lv2_ON_latitude_mean', 'GP_hpg_lv2_ON_latitude_max',
    'GP_hpg_lv2_ON_latitude_min', 'GP_hpg_lv2_ON_longitude_mean',
    'GP_hpg_lv2_ON_longitude_max', 'GP_hpg_lv2_ON_longitude_min',
    'GP_hpg_lv3_ON_latitude_mean', 'GP_hpg_lv3_ON_latitude_max',
    'GP_hpg_lv3_ON_latitude_min', 'GP_hpg_lv3_ON_longitude_mean',
    'GP_hpg_lv3_ON_longitude_max', 'GP_hpg_lv3_ON_longitude_min',
    'weight2', 'weight3', 'weight4', 'weight5',
    'lon_plus_lat_air', 'lat_to_mean_lat_air_lv1',
    'lat_to_max_lat_air_lv1', 'lat_to_min_lat_air_lv1',
    'lon_to_mean_lon_air_lv1', 'lon_to_max_lon_air_lv1',
    'lon_to_min_lon_air_lv1', 'lat_to_mean_lat_air_lv2',
    'lat_to_max_lat_air_lv2', 'lat_to_min_lat_air_lv2',
    'lon_to_mean_lon_air_lv2', 'lon_to_max_lon_air_lv2',
    'lon_to_min_lon_air_lv2', 'lat_to_mean_lat_hpg_lv1',
    'lat_to_max_lat_hpg_lv1', 'lat_to_min_lat_hpg_lv1',
    'lon_to_mean_lon_hpg_lv1', 'lon_to_max_lon_hpg_lv1',
    'lon_to_min_lon_hpg_lv1', 'lat_to_mean_lat_hpg_lv2',
    'lat_to_max_lat_hpg_lv2', 'lat_to_min_lat_hpg_lv2',
    'lon_to_mean_lon_hpg_lv2', 'lon_to_max_lon_hpg_lv2',
    'lon_to_min_lon_hpg_lv2',
    'GP_dow_ON_visitors_mean_log1p', 'GP_dow_ON_visitors_max_log1p',
    'GP_dow_ON_visitors_min_log1p', 'GP_dow_ON_visitors_median_log1p',
    'GP_is_weekend_ON_visitors_mean_log1p',
    'GP_is_weekend_ON_visitors_max_log1p',
    'GP_is_weekend_ON_visitors_min_log1p',
    'GP_is_weekend_ON_visitors_median_log1p',
    'GP_is_golden_week_ON_visitors_mean_log1p',
    'GP_is_golden_week_ON_visitors_max_log1p',
    'GP_is_golden_week_ON_visitors_min_log1p',
    'GP_is_golden_week_ON_visitors_median_log1p',
    'GP_is_month_str_ON_visitors_mean_log1p',
    'GP_is_month_str_ON_visitors_max_log1p',
    'GP_is_month_str_ON_visitors_min_log1p',
    'GP_is_month_str_ON_visitors_median_log1p',
    'GP_air_store_id_ON_visitors_mean_log1p',
    'GP_air_store_id_ON_visitors_max_log1p',
    'GP_air_store_id_ON_visitors_min_log1p',
    'GP_air_store_id_ON_visitors_median_log1p',
    'GP_air_store_id_ON_visitors_sum_log1p', 'reserve_visitors_log1p',
    'GP_all_store_id_ON_reserve_visitors_mean_log1p',
    'GP_all_store_id_ON_reserve_visitors_max_log1p',
    'GP_all_store_id_ON_reserve_visitors_min_log1p',
    'GP_all_store_id_ON_reserve_visitors_count_log1p',
    'GP_all_store_id_ON_reserve_visitors_sum_log1p',
    'GP_all_store_id_ON_reserve_ahead_in_days_mean_log1p',
    'GP_all_store_id_ON_reserve_ahead_in_days_max_log1p',
    'GP_all_store_id_ON_reserve_ahead_in_days_min_log1p',
    'GP_visit_date_ON_reserve_visitors_mean_all_log1p',
    'GP_visit_date_ON_reserve_visitors_max_all_log1p',
    'GP_visit_date_ON_reserve_visitors_min_all_log1p',
    'GP_visit_date_ON_reserve_visitors_count_all_log1p',
    'GP_visit_date_ON_reserve_visitors_sum_all_log1p',
    'GP_visit_date_ON_reserve_ahead_in_days_mean_all_log1p',
    'GP_visit_date_ON_reserve_ahead_in_days_max_all_log1p',
    'GP_visit_date_ON_reserve_ahead_in_days_min_all_log1p',
    'GP_visit_date_all_store_id_ON_reserve_visitors_mean_log1p',
    'GP_visit_date_all_store_id_ON_reserve_visitors_max_log1p',
    'GP_visit_date_all_store_id_ON_reserve_visitors_min_log1p',
    'GP_visit_date_all_store_id_ON_reserve_visitors_count_log1p',
    'GP_visit_date_all_store_id_ON_reserve_visitors_sum_log1p',
    'GP_visit_date_all_store_id_ON_reserve_ahead_in_days_mean_log1p',
    'GP_visit_date_all_store_id_ON_reserve_ahead_in_days_max_log1p',
    'GP_visit_date_all_store_id_ON_reserve_ahead_in_days_min_log1p',
    'GP_air_store_id_dow_holiday_flg_ON_visitors_mean_log1p',
    'GP_air_store_id_dow_holiday_flg_ON_visitors_max_log1p',
    'GP_air_store_id_dow_holiday_flg_ON_visitors_min_log1p',
    'GP_air_store_id_dow_holiday_flg_ON_visitors_median_log1p',
    'GP_air_store_id_is_golden_week_ON_visitors_mean_log1p',
    'GP_air_store_id_is_golden_week_ON_visitors_max_log1p',
    'GP_air_store_id_is_golden_week_ON_visitors_min_log1p',
    'GP_air_store_id_is_golden_week_ON_visitors_median_log1p'
               ]

int_feats = [
    'GP_latitude_longitude_ON_air_store_id_count',
    'GP_air_lv1_ON_air_store_id_count',
    'GP_air_lv1_air_lv2_ON_air_store_id_count',
    'GP_air_lv1_air_lv2_air_lv3_ON_air_store_id_count',
    'GP_air_genre_name_ON_air_store_id_count',
    'GP_air_genre_name_air_lv1_ON_air_store_id_count',
    'GP_air_genre_name_air_lv1_air_lv2_ON_air_store_id_count',
    'GP_air_genre_name_air_lv1_air_lv2_air_lv3_ON_air_store_id_count'
]

cat_feats = ['day', 'month', 'year', 'dow', 'doy', 'woy', 'holiday_flg']

bool_feats = ['is_weekend', 'is_golden_week', 'is_month_end', 'is_month_str']

features = float_feats + int_feats + bool_feats + cat_feats

def features_set_f2():
    return features, cat_feats + bool_feats
